// Generated by tools/generate-battle-terrain-manifest.mjs.
export const BATTLE_TERRAIN_ASSET_UUIDS = {
  "battle_atmosphere.png": "891a6e74-1361-4d6d-a749-6a60a29d9f36",
  "battle_road_overlay.png": "186d41d1-cb00-443c-bfb6-a8436228a4c2",
  "battle_ruins_left.png": "9eca0052-34fe-480d-b8c3-d8869602e523",
  "battle_ruins_right.png": "5636c52c-e3f2-4115-840b-976db0fa6ded",
  "battle_terrain_base_720x1280.png": "07133855-9c0b-4c3c-86f2-f1a921da72c3",
  "battle_wall_back.png": "00245cae-eabb-4a00-95ab-e73edfad5207",
  "battle_wall_front.png": "facb78df-6584-4956-aba1-1ae6aeb45429"
} as const;
